p8105_hw1_lg3450
================
Luyun Ge
2025-09-20

R Markdown file by Luyun Ge for P8105 Homework1.

step 1: load required library

``` r
library(moderndive)
library(ggplot2)
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ lubridate 1.9.4     ✔ tibble    3.3.0
    ## ✔ purrr     1.1.0     ✔ tidyr     1.3.1
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

# Problem1

We loaded the required dataset for problem1.

``` r
data("early_january_weather")
```

Then we listed all variables in this dataset, calculated the size of
this dataset and the mean temperature.

``` r
names(early_january_weather) #listed all variables in dataset
```

    ##  [1] "origin"     "year"       "month"      "day"        "hour"      
    ##  [6] "temp"       "dewp"       "humid"      "wind_dir"   "wind_speed"
    ## [11] "wind_gust"  "precip"     "pressure"   "visib"      "time_hour"

``` r
nrow(early_january_weather) #number of rows
```

    ## [1] 358

``` r
ncol(early_january_weather) #number of columns
```

    ## [1] 15

``` r
mean(early_january_weather$temp) #mean temperature
```

    ## [1] 39.58212

The `early_january_weather dataset` has 15 variables: `origin`, `year`,
`month`, `day`, `hour`, `temp`, `dewp`, `humid`, `wind_dir`,
`wind_speed`, `wind_gust`, `precip`, `pressure`, `visib`, `time_hour`.
The dataset has 358 rows and 15 columns. The mean temperarture of early
January is 39.58212 Fahrenheit.
